Added color and opacity options
jpedroribeiro/Baseliner pull request #2
Opened 2016-09-30 19:47 UTC by igormatos

2016-10-01 14:16 UTC, jpedroribeiro requested changes
Hi there igormatos,

Really like the updates proposed in this PR! Good job!
The idea of using SVG instead is smart and I wish I had thought about that sooner.

My only concern is the use of those JS files for the colour picker. I don't want this extension to have dependencies like that and it feels like it could be achieved just by using <input type=color> (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color)

I've also made some comments more related about readability and code standards. 

What do you think?

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/baseliner_v1.0.0.js
> +	baselinerColor: '#cccccc',
for readability, could you indent the lines above to match the ones line on line 12?

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/baseliner_v1.0.0.js
> +			this.opacity = this.getOpacityDataAttribute();
why not call it `baselineOpacity` instead of `opacity`? so it follows the pattern.

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/baseliner_v1.0.0.js
> +	 * @param newColor
you are also sending `newOpacity` so it should be on the docs comment like you did for `newColor`

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/baseliner_v1.0.0.js
> +	// update: function(newBaseline, newTop) {
can we get rid of this comment line?

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/baseliner_v1.0.0.js
>  	 */
can you add the comments for the new params you added? (`opacity`, `color`)

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/baseliner_v1.0.0.js
> +	setDataAttributes: function(baseline, top, opacity, color){
if you are going to send the options (baseline, top, opacity, color) in different methods, can you always use the same order? `update()` is different than `setDataAttribute` and it can become easy to make mistakes in the future

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/color.all.min.js
> +//# sourceMappingURL=colorPicker.js.map
what is this file? can we remove it please.

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/jsColorPicker.min.js
> +//# sourceMappingURL=../colorPicker.js.map
can we remove this file?

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/jscolor-example.html
> +</html>
can we remove this file?

2016-10-01 14:16 UTC, jpedroribeiro commented on jscolor.min.js
> + */"use strict";window.jscolor||(window.jscolor=function(){var e={register:function(){e.attachDOMReadyEvent(e.init),e.attachEvent(document,"mousedown",e.onDocumentMouseDown),e.attachEvent(document,"t
could we not have this file?

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/styles.css
> +    padding-left: 8px;
can you fix indentation here please

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/styles.css
> +  /*width: 100%;*/
can we remove this comment please

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/picker.js
> +  });
do we need this file?

2016-10-01 14:16 UTC, jpedroribeiro commented on chrome_extension/manifest.json
> +    "line.svg", "main.js","jsColorPicker.min.js", "picker.js"]
is this necessary?

2016-10-01 16:21 UTC, igormatos commented
@jpedroribeiro I will fix these things, thanks for the review. Some points I didn't pay attention. I am not a javascript developer, and some things were new to me hehe :p

2016-10-01 16:52 UTC, igormatos commented
I've updated the PR. Indented the lines you asked, removed the some files and reordered the methods parameters. But the extension stills use the JS script to the color picker, i had some problem trying to use the input type="color", because when it opens the color picker window, it closes the extension tab, loosing the context, so i could't listen to onChange event. If you can make it work, I agree, it would be better, was my first time playing with chrome extension :))

2016-10-02 14:43 UTC, jpedroribeiro commented
Ah I see. Yeah, it makes perfect sense.

Would you mind giving me access to edit your PR branch? 
There are some updates I'd like to do before merging it into the master branch, like updating the Chrome Store  / website images. 

Here's some info if you need assistance: https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

2016-10-02 15:24 UTC, igormatos commented
No problem. Edit allowed :)

2016-10-05 12:08 UTC, igormatos commented
You can remove the background image that was used too.

2016-10-09 14:47 UTC, jpedroribeiro approved these changes

2016-10-09 14:47 UTC, merged