Change way to display line from svg to gradient. Stored Force Height …
jpedroribeiro/Baseliner pull request #7
Opened 2016-11-22 12:18 UTC by borracciaBlu

- Change the way to display line from svg to gradient. Now we can use fractions of px.
- Stored Force Height Flag.

2016-11-22 12:21 UTC, jpedroribeiro commented on chrome_extension/baseliner.js
>  	 */
could you update the @params to cater for the new parameters please

2016-11-22 12:22 UTC, jpedroribeiro commented on chrome_extension/baseliner.js
>  	 */
same here

2016-11-22 12:23 UTC, jpedroribeiro commented on chrome_extension/main.js
>      if (event.key === "ArrowUp" && event.target === $extensionOpacity && $extensionOpacity.value < 100) $extensionOpacity.value++;
ah, well spotted!

2016-11-22 12:31 UTC, borracciaBlu commented on chrome_extension/baseliner.js
>  	 */
it should be fine now

2016-11-22 12:36 UTC, borracciaBlu commented on chrome_extension/main.js
>      if (event.key === "ArrowUp" && event.target === $extensionOpacity && $extensionOpacity.value < 100) $extensionOpacity.value++;
thanks

2016-11-27 16:13 UTC, jpedroribeiro requested changes
I like the idea of using gradients instead. Much more performant and customisable I believe.
I've added some comments regarding CSS which seem to be hiding the colour input.

2016-11-27 16:13 UTC, jpedroribeiro commented on chrome_extension/styles.css
>          text-align: right;
All these CSS updates are pushing the colour input to below the visible area.
Adding `white-space: nowrap;` to the .fieldInput will make sure it stays where it should.

2016-11-27 16:13 UTC, jpedroribeiro commented on chrome_extension/styles.css
> +.cp-opacity, .cp-memo {
would you mind adding a comment stating that these styles are to overwrite the jscolor plugin classes and hide opacity menu from the popup.

2016-11-28 09:12 UTC, borracciaBlu commented
It should be fine now. Let me know. Thanks for the feedback.

2016-12-01 14:01 UTC, jpedroribeiro approved these changes

2016-12-01 14:02 UTC, merged